[psql]
dbname = "template"
user = "postgres"
pass = "admin"
host = "127.0.0.1"
port = "5432"
sslmode = "disable"

[mysql]
dbname = "template"
user = "postgres"
pass = "admin"
host = "127.0.0.1"
port = "3306"
